import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";
import twilio from "twilio";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // AI Proxy Endpoints
  // This allows the user to swap Gemini for Qwen or any other API later
  app.post("/api/ai/generate", async (req, res) => {
    const { prompt, systemInstruction, responseMimeType, responseSchema } = req.body;
    
    try {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        return res.status(500).json({ error: "GEMINI_API_KEY is not configured" });
      }

      const ai = new GoogleGenAI({ apiKey });
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
          systemInstruction,
          responseMimeType: responseMimeType || "text/plain",
          responseSchema: responseSchema || undefined,
        },
      });

      res.json({ text: response.text });
    } catch (error: any) {
      console.error("AI Generation Error:", error);
      res.status(500).json({ error: error.message });
    }
  });

  // WhatsApp Report Endpoint
  app.post("/api/reports/whatsapp", async (req, res) => {
    const { 
      studentName, 
      parentPhone, 
      subject, 
      score, 
      totalMarks, 
      isExam, 
      struggledQuestions, 
      improvementNotes, 
      answeringSuggestions 
    } = req.body;

    try {
      const accountSid = process.env.TWILIO_ACCOUNT_SID;
      const authToken = process.env.TWILIO_AUTH_TOKEN;
      const fromNumber = process.env.TWILIO_WHATSAPP_NUMBER;

      if (!accountSid || !authToken || !fromNumber) {
        console.warn("Twilio credentials not configured. Skipping WhatsApp report.");
        return res.status(200).json({ status: "skipped", message: "Twilio not configured" });
      }

      const client = twilio(accountSid, authToken);
      const date = new Date().toLocaleDateString('en-GB', { 
        day: 'numeric', 
        month: 'long', 
        year: 'numeric' 
      });

      // Simple cleanup for phone number (remove spaces, ensure +)
      let formattedPhone = parentPhone.replace(/\s+/g, '');
      if (!formattedPhone.startsWith('+')) {
        formattedPhone = '+' + formattedPhone;
      }

      const percentage = totalMarks > 0 ? Math.round((score / totalMarks) * 100) : 0;
      const type = isExam ? "EXAM" : "PRACTICE";
      
      const grade = percentage >= 90 ? 'A*' : 
                    percentage >= 80 ? 'A' : 
                    percentage >= 70 ? 'B' : 
                    percentage >= 60 ? 'C' : 
                    percentage >= 50 ? 'D' : 
                    percentage >= 40 ? 'E' : 'U';

      // Enhanced WhatsApp Message Formatting
      const message = `
*IGCSE PREP PERFORMANCE REPORT* 📊
----------------------------------
*Student:* ${studentName}
*Date:* ${date}
*Type:* ${type}
*Subject:* ${subject}
----------------------------------
*SCORE:* ${score} / ${totalMarks} (${percentage}%)
*PREDICTED GRADE:* ${grade}
----------------------------------

*AREAS FOR IMPROVEMENT:*
${improvementNotes || "Keep practicing all topics to maintain excellence."}

*QUESTIONS STRUGGLED WITH:*
${struggledQuestions?.length > 0 
  ? struggledQuestions.slice(0, 3).map((q: string, i: number) => `• ${q}`).join('\n')
  : "None! Excellent performance across all questions."}

*REVISION SUGGESTIONS:*
${answeringSuggestions || "Focus on keyword usage and structuring your answers according to Cambridge standards."}

_This report was auto-generated by IGCSE Prep App._
      `.trim();

      await client.messages.create({
        body: message,
        from: `whatsapp:${fromNumber}`,
        to: `whatsapp:${formattedPhone}`
      });

      res.json({ status: "success" });
    } catch (error: any) {
      console.error("WhatsApp Error:", error);
      res.status(500).json({ error: error.message });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  // Telegram Report Endpoint
app.post('/api/reports/telegram', async (req, res) => {
  const { chatId, message } = req.body;
  const botToken = process.env.TELEGRAM_BOT_TOKEN;

  if (!botToken) {
    return res.status(500).json({ error: 'TELEGRAM_BOT_TOKEN not configured' });
  }

  try {
    const response = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text: message,
        parse_mode: 'HTML'
      })
    });

    const data = await response.json();
    if (!data.ok) throw new Error(data.description);

    res.json({ success: true });
  } catch (error) {
    console.error('Telegram Error:', error);
    res.status(500).json({ error: 'Failed to send Telegram message' });
  }
});

app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
